# Generated by Django 2.1.5 on 2019-01-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget_result',
            old_name='Pship_num',
            new_name='Pship_number',
        ),
        migrations.RenameField(
            model_name='cost_result',
            old_name='Pship_num',
            new_name='Pship_number',
        ),
        migrations.RenameField(
            model_name='fuel_rent',
            old_name='Pship_num',
            new_name='Pship_number',
        ),
        migrations.RenameField(
            model_name='pcargo',
            old_name='Pship_num',
            new_name='Pship_number',
        ),
        migrations.RenameField(
            model_name='pport',
            old_name='Pship_num',
            new_name='Pship_number',
        ),
        migrations.RenameField(
            model_name='pship_pport',
            old_name='Pship_num',
            new_name='Pship_number',
        ),
    ]
