# Generated by Django 2.1.5 on 2019-01-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190116_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pship',
            name='Pship_hovel',
            field=models.FloatField(max_length=20, verbose_name='舱容'),
        ),
        migrations.AlterField(
            model_name='pship',
            name='Pship_load',
            field=models.FloatField(max_length=20, verbose_name='载重吨'),
        ),
    ]
